{{cookiecutter.project_name}}/noxfile.py

cjolowicz/cookiecutter-hypermodern-python-instance#7

Decrease verbosity of safety

---

{{cookiecutter.project_name}}/.readthedocs.yml

Fixes #16 
cjolowicz/cookiecutter-hypermodern-python-instance#19

Upgrade Read the Docs to Python 3.8

---

{{cookiecutter.project_name}}/README.md

Add badges

---

.github/workflows/tests.yml
{{cookiecutter.project_name}}/.github/workflows/tests.yml
{{cookiecutter.project_name}}/noxfile.py
{{cookiecutter.project_name}}/poetry.lock
{{cookiecutter.project_name}}/pyproject.toml

Support Python 3.6

---

CODE_OF_CONDUCT.md
{{cookiecutter.project_name}}/CODE_OF_CONDUCT.md
{{cookiecutter.project_name}}/docs/CODE_OF_CONDUCT.md
{{cookiecutter.project_name}}/docs/index.rst

Add Code of Conduct

---

README.md
{{cookiecutter.project_name}}/.flake8
{{cookiecutter.project_name}}/noxfile.py
{{cookiecutter.project_name}}/poetry.lock
{{cookiecutter.project_name}}/pyproject.toml

Add pep8-naming to linter suite

---

.github/release-drafter.yml
.github/workflows/tests.yml
CODE_OF_CONDUCT.md
README.md
{{cookiecutter.project_name}}/.github/release-drafter.yml
{{cookiecutter.project_name}}/.github/workflows/coverage.yml
{{cookiecutter.project_name}}/.github/workflows/release.yml
{{cookiecutter.project_name}}/.github/workflows/test-pypi.yml
{{cookiecutter.project_name}}/.github/workflows/tests.yml
{{cookiecutter.project_name}}/.pre-commit-config.yaml
{{cookiecutter.project_name}}/CODE_OF_CONDUCT.md

Additions:
- Prettier pre-commit hook
- Added `prose-wrap` option and set `print-width` to 88 to match Black styling
- Formatted all Markdown and YAML files to be compliant to the pre-commit rules

Add Prettier pre-commit hook

---

{{cookiecutter.project_name}}/.github/workflows/coverage.yml
{{cookiecutter.project_name}}/.github/workflows/release.yml
{{cookiecutter.project_name}}/.github/workflows/test-pypi.yml
{{cookiecutter.project_name}}/.github/workflows/tests.yml

cjolowicz/cookiecutter-hypermodern-python-instance#44

Upgrade to Poetry 1.0.5

---

{{cookiecutter.project_name}}/.github/workflows/coverage.yml
{{cookiecutter.project_name}}/noxfile.py
{{cookiecutter.project_name}}/poetry.lock
{{cookiecutter.project_name}}/pyproject.toml

cjolowicz/cookiecutter-hypermodern-python-instance#56
* Use GitHub Action from Codecov
* Do not invoke codecov from Nox
* Remove codecov

Use GitHub Action from Codecov

---

{{cookiecutter.project_name}}/CONTRIBUTING.md
{{cookiecutter.project_name}}/docs/CONTRIBUTING.md
{{cookiecutter.project_name}}/docs/index.rst

Add Contributor Guide

---

docs/guide.rst
{{cookiecutter.project_name}}/noxfile.py
{{cookiecutter.project_name}}/poetry.lock
{{cookiecutter.project_name}}/pyproject.toml

Use sphinx-autobuild in interactive sessions

---

.github/workflows/reset-instance.yml

Add workflow to reset instance on push to master

---

{{cookiecutter.project_name}}/.github/workflows/coverage.yml

cjolowicz/cookiecutter-hypermodern-python-instance#93
Closes #102

Fix Codecov uploads when target percentage is not reached

---

{{cookiecutter.project_name}}/codecov.yml

cjolowicz/cookiecutter-hypermodern-python-instance#90

Configure Codecov to require 100% code coverage

---

.github/workflows/tests.yml
{{cookiecutter.project_name}}/.github/workflows/coverage.yml
{{cookiecutter.project_name}}/.github/workflows/pre-commit.yml
{{cookiecutter.project_name}}/.github/workflows/release.yml
{{cookiecutter.project_name}}/.github/workflows/test-pypi.yml
{{cookiecutter.project_name}}/.github/workflows/tests.yml

Force colorized output for Nox and Poetry in CI workflows.

Enable colorized output in CI

---

README.rst
docs/guide.rst
{{cookiecutter.project_name}}/noxfile.py
{{cookiecutter.project_name}}/poetry.lock
{{cookiecutter.project_name}}/pyproject.toml

Remove pytype

---

docs/guide.rst
{{cookiecutter.project_name}}/.github/workflows/pre-commit.yml
{{cookiecutter.project_name}}/.github/workflows/tests.yml

Support Windows and macOS on GitHub Actions

---

LICENSE.rst
docs/guide.rst
docs/index.rst
docs/license.rst
{{cookiecutter.project_name}}/LICENSE.rst
{{cookiecutter.project_name}}/docs/index.rst
{{cookiecutter.project_name}}/docs/license.rst

cjolowicz/cookiecutter-hypermodern-python-instance#128

Convert License to reStructuredText

---

.github/workflows/pre-commit.yml
.pre-commit-config.yaml
docs/guide.rst

Support pre-commit in Cookiecutter

---

.pre-commit-config.yaml
{{cookiecutter.project_name}}/.pre-commit-config.yaml

https://github.com/prettier/prettier/blob/master/CHANGELOG.md#205

Bump prettier from 2.0.4 to 2.0.5

---

.dependabot/config.yml
README.rst
docs/guide.rst
docs/quickstart.rst
{{cookiecutter.project_name}}/.dependabot/config.yml

cjolowicz/cookiecutter-hypermodern-python-instance#134

Use dependabot for requirements and GitHub Actions

---

README.rst
docs/guide.rst

Closes #90 
TODO: Document automation rules

Document GitHub webhook for Read the Docs

---

docs/guide.rst
{{cookiecutter.project_name}}/.pre-commit-config.yaml

cjolowicz/cookiecutter-hypermodern-python-instance#138

Add pre-commit hook `check-added-large-files`

---

.github/workflows/docs.yml
.github/workflows/pre-commit.yml
.github/workflows/reset-instance.yml
.github/workflows/tests.yml
{{cookiecutter.project_name}}/.github/workflows/coverage.yml
{{cookiecutter.project_name}}/.github/workflows/docs.yml
{{cookiecutter.project_name}}/.github/workflows/pre-commit.yml
{{cookiecutter.project_name}}/.github/workflows/release.yml
{{cookiecutter.project_name}}/.github/workflows/test-pypi.yml
{{cookiecutter.project_name}}/.github/workflows/tests.yml

Closes #195 
cjolowicz/cookiecutter-hypermodern-python-instance#139

Pin GitHub Actions

---

.github/workflows/pre-commit.yml
.github/workflows/tests.yml

https://github.com/actions/cache/issues/144

Change cache key to workaround an issue in actions/cache

---

{{cookiecutter.project_name}}/noxfile.py

cjolowicz/cookiecutter-hypermodern-python-instance#143

Do not install package in mypy session

---

hooks/post_gen_project.py
{{cookiecutter.project_name}}/.cookiecutter.json

This file records the JSON context used when generating the project. It
allows to upgrade the project with changes from the Cookiecutter, using
tools like [cupper].
[cupper]: https://github.com/senseyeio/cupper

Add .cookiecutter.json to project

---

docs/_static/custom.css
noxfile.py

Display table captions like admonition titles

---

docs/guide.rst
{{cookiecutter.project_name}}/.pre-commit-config.yaml
{{cookiecutter.project_name}}/noxfile.py
{{cookiecutter.project_name}}/poetry.lock
{{cookiecutter.project_name}}/pyproject.toml
{{cookiecutter.project_name}}/tests/test_main.py

Sort imports with reorder-python-imports

---

{{cookiecutter.project_name}}/.gitignore

cjolowicz/cookiecutter-hypermodern-python-instance#155

Ignore .mypy_cache/ in subdirectories

---

docs/guide.rst
{{cookiecutter.project_name}}/noxfile.py
{{cookiecutter.project_name}}/poetry.lock
{{cookiecutter.project_name}}/pyproject.toml

Add pre-commit to Poetry and Nox.
Rationale:
- Nox as single entry point
- mirrors common practice of having a tox session for pre-commit
- flake8 can still be triggered via Nox after its session is removed
- track pre-commit as a development dependency
Closes #223

Add Nox session for pre-commit

---

.dependabot/config.yml

Use Dependabot for dependencies in template directory

---

.github/workflows/pre-commit.yml
.github/workflows/tests.yml
{{cookiecutter.project_name}}/.github/workflows/release.yml
{{cookiecutter.project_name}}/.github/workflows/tests.yml

Do not cache pre-commit environments on Windows

---

.github/workflows/constraints.txt
.github/workflows/tests.yml

Remove redundant pre-commit step in Tests workflow (Cookiecutter)

---

.dependabot/config.yml

This reverts commit efcd0c220486ac7ddadc3e871463d984676b09a2.
Reverts #259 
Closes #260 
Closes #261

Revert "Use Dependabot for dependencies in template directory (#259)"

---

.github/workflows/docs.yml
.github/workflows/pre-commit.yml
.github/workflows/tests.yml
docs/guide.rst
{{cookiecutter.project_name}}/.github/workflows/coverage.yml
{{cookiecutter.project_name}}/.github/workflows/docs.yml
{{cookiecutter.project_name}}/.github/workflows/tests.yml

Trigger checks on pull requests

---

CONTRIBUTORS.rst
docs/contributors.rst
docs/index.rst

Add CONTRIBUTORS.rst

---

{{cookiecutter.project_name}}/README.rst
{{cookiecutter.project_name}}/docs/reference.rst

Fix reST headings in generated documentation

---

{{cookiecutter.project_name}}/noxfile.py

Do not skip coverage session when tests fail

---

{{cookiecutter.project_name}}/.github/workflows/tests.yml

Use nox --python instead of session suffixes in Tests workflow

---

README.rst
docs/guide.rst

This is a feature release outside of the bi-monthly release cadence. During the initial development phase, releases are more frequent. The next release is scheduled for 2020.7.15. See the [GitHub Releases](../releases) page for details about this release.
This PR changes references to the current stable release in the documentation.

Release 2020.6.15

---

docs/index.rst

Fix stale version in Sphinx documentation

---

docs/guide.rst

Fix reversal of "kebab case" and "snake case" in User Guide

---

{{cookiecutter.project_name}}/noxfile.py

The implementation of `install_package` in noxfile.py introduced in #488 uses `poetry install --no-root` to install the package dependencies. Unfortunately, Poetry ignores an activated virtual environment when there is also a Poetry environment. As a result, the dependencies were installed into an existing Poetry environment instead of the Nox session. This breaks all sessions that need the package installed, in the presence of a Poetry environment.
Instead, switch back to the previous implementation, which uses pip to install from a requirements file exported from Poetry. This means we now need to generate and cache two requirements files: with and without development dependencies. These are named "requirements.txt" and "dev-requirements.txt", and each have their corresponding hash file …

Do not install dependencies to Poetry environment from Nox session

---

.github/workflows/tests.yml
docs/guide.rst
{{cookiecutter.project_name}}/.github/workflows/tests.yml
{{cookiecutter.project_name}}/noxfile.py

- Create docs-build session on nox
- Update tests to execute docs-build instead of docs
- Update documention on nox sessions and description of tests workflow.
Closes #461

Add docs-build session

---

{{cookiecutter.project_name}}/.github/workflows/tests.yml

Pin actions/upload-artifact to v2.2.0

---

docs/guide.rst

Update documentation to Python 3.8.6

---

docs/guide.rst

Closes #367
Closes #553
Closes #554
Closes #555
Closes #559

Minor improvements to the User Guide

---

.github/workflows/constraints.txt

Pin pre-commit to 2.8.2 in .github/workflows/constraints.txt

---

{{cookiecutter.project_name}}/noxfile.py

See https://github.com/tornadoweb/tornado/issues/2981

Ignore CVE-2020-28476 affecting all versions of tornado

---

{{cookiecutter.project_name}}/poetry.lock

Bump jinja2 from 2.11.2 to 2.11.3

Bump jinja2 from 2.11.2 to 2.11.3

---

{{cookiecutter.project_name}}/poetry.lock

Bump pyyaml from 5.3.1 to 5.4.1

Bump pyyaml from 5.3.1 to 5.4.1

---

{{cookiecutter.project_name}}/poetry.lock

Bump urllib3 from 1.26.3 to 1.26.4

Bump urllib3 from 1.26.3 to 1.26.4

---

{{cookiecutter.project_name}}/.github/workflows/release.yml
{{cookiecutter.project_name}}/.github/workflows/tests.yml

Bump actions/setup-python from v2.2.1 to v2.2.2

---

{{cookiecutter.project_name}}/mypy.ini

Simplify mypy.ini using the strict setting

---

docs/guide.rst

Update User Guide to reflect recent changes in mypy.ini

---

docs/guide.rst

Include Labeler workflow in "Files and Directories" table in User Guide

---

{{cookiecutter.project_name}}/noxfile.py

Improve error message when nox-poetry is not installed

---

{{cookiecutter.project_name}}/.gitignore

Ignore per-machine coverage data files

---

.pre-commit-config.yaml
{{cookiecutter.project_name}}/.pre-commit-config.yaml

Update prettier hook to new mirrors-prettier repo

---

docs/guide.rst
{{cookiecutter.project_name}}/.github/workflows/tests.yml
{{cookiecutter.project_name}}/noxfile.py

Bump docs and docs-build session python to 3.9

---

docs/guide.rst

Update link on poetry version constraints

---

{{cookiecutter.project_name}}/poetry.lock

Bump click from 7.1.2 to 8.0.1 in poetry.lock

---

{{cookiecutter.project_name}}/pyproject.toml

Require click 8.x

---

README.rst
docs/guide.rst
docs/index.rst
docs/quickstart.rst

* Remove types-click from Nox session for mypy (#952) @cjolowicz
* Remove reference to mypy.ini from User Guide (#950) @cjolowicz
* Update poetry.lock (#951) @cjolowicz

Release 2021.6.16

---

cookiecutter.json
docs/guide.rst
{{cookiecutter.project_name}}/README.rst
{{cookiecutter.project_name}}/pyproject.toml

Closes #963 
- :package: Add `development_status` project variable to cookiecutter.json
- :package: Add Trove classifier for Development Status
- :books: Add badge for development status on PyPI
- :books: Document `development_status` project variable in User Guide

Add Trove classifier for Development Status

---

{{cookiecutter.project_name}}/poetry.lock

Bump babel from 2.9.0 to 2.9.1

Bump babel from 2.9.0 to 2.9.1

---

docs/conf.py

👷 Ignore our RTD page when checking links in documentation

---

docs/guide.rst

📚 [docs] Add instructions for installation on Windows

---

docs/guide.rst

- 📚 [guide] Update documentation for pyproject.toml
- 📚 [guide] Why we remove upper bounds from version constraints

📚 [guide] Why we remove upper bounds from version constraints

---

README.rst
docs/guide.rst

Closes #1131 
- 📚 [README] Add MyST to features
- 📚 [guide] Update User Guide after switch to MyST docs

📚 Update User Guide and README after switch to MyST

---

{{cookiecutter.project_name}}/CODE_OF_CONDUCT.md

Upgrade CODE_OF_CONDUCT.md to Contributor Covenant 2.1

---

{{cookiecutter.project_name}}/README.md
{{cookiecutter.project_name}}/docs/index.md

fix license links

---

{{cookiecutter.project_name}}/README.md
{{cookiecutter.project_name}}/docs/index.md

Link license badge to project license

---

{{cookiecutter.project_name}}/README.md

__remove duplicate link in readme__

fix issue #1195 remove duplicate link
