{{cookiecutter.project_name}}/.flake8
{{cookiecutter.project_name}}/.gitignore
{{cookiecutter.project_name}}/noxfile.py

Fixes #3 
cjolowicz/cookiecutter-hypermodern-python-instance#6
* Ignore /dist/
* Ignore ANN101 (missing type annotation for self in method)
* Add Poetry helper class for Nox
* Use Poetry.export in install_with_constraints
* Update docstring for install_with_constraints
* Drop kwargs parameter for install_with_constraints
* Rename install_with_constraints to install
* Use Poetry.export in safety session
* Add Poetry.version
* Add Poetry.build
* Add install_package to install wheel into Nox sessions
* Use install_package instead of `poetry install --no-dev`

Install package as wheel inside Nox sessions

---

{{cookiecutter.project_name}}/pyproject.toml
{{cookiecutter.project_name}}/src/{{cookiecutter.package_name}}/__main__.py

Fixes #9 
cjolowicz/cookiecutter-hypermodern-python-instance#24
* Allow script invocation via python -m
* Add module docstring
* Disable coverage for __main__

Support running with `python -m <package>`

---

{{cookiecutter.project_name}}/docs/index.rst
{{cookiecutter.project_name}}/pyproject.toml

Fixes #13 
cjolowicz/cookiecutter-hypermodern-python-instance#20
* Link GitHub Releases from Sphinx documentation
* Link GitHub Releases from PyPI page

Add GitHub Releases link to PyPI and Read the Docs

---

README.md
{{cookiecutter.project_name}}/.flake8
{{cookiecutter.project_name}}/noxfile.py
{{cookiecutter.project_name}}/poetry.lock
{{cookiecutter.project_name}}/pyproject.toml

This PR adds [flake8-rst-docstrings](https://github.com/peterjc/flake8-rst-docstrings) linting rules by
- Adding a dependency to Poetry files
- Adding `RST` validation code to `.flake8`
- Adding flake8-rst-docstrings installation to Nox lint session
- Adding flake8-rst-docstrings description to `README.md`

Add flake8-rst-docstrings to linting rules

---

{{cookiecutter.project_name}}/poetry.lock

- Bump jinja2 from 2.11.1 to 2.11.2
cjolowicz/cookiecutter-hypermodern-python-instance#89
Bumps [jinja2](https://github.com/pallets/jinja) from 2.11.1 to 2.11.2.
- [Release notes](https://github.com/pallets/jinja/releases)
- [Changelog](https://github.com/pallets/jinja/blob/master/CHANGES.rst)
- [Commits](https://github.com/pallets/jinja/compare/2.11.1...2.11.2)
Signed-off-by: dependabot-preview[bot] <support@dependabot.com>
Co-authored-by: dependabot-preview[bot] <27856297+dependabot-preview[bot]@users.noreply.github.com>

Upgrade dependencies

---

docs/guide.rst
{{cookiecutter.project_name}}/.github/workflows/coverage.yml
{{cookiecutter.project_name}}/noxfile.py

There is no longer any need for the coverage session, now that we upload to Codecov using their GitHub Action.
The coverage session was still used to generate an XML coverage report. Instead, the Coverage workflow now passes `--cov-report=xml` to the tests session.
cjolowicz/cookiecutter-hypermodern-python-instance#94

Remove coverage session

---

docs/guide.rst
{{cookiecutter.project_name}}/codecov.yml

Users can always click the failed coverage check.

Disable codecov comments

---

{{cookiecutter.project_name}}/.github/workflows/pre-commit.yml

The cache key for the pre-commit workflow did not include the Python version,
due to an `IndentationError` in the Python code used to generate the key.

Fix CI cache for pre-commit workflow

---

.github/release-drafter.yml
README.md
docs/guide.rst
{{cookiecutter.project_name}}/.github/release-drafter.yml

The `build` label is kept for backwards compatibility. It should be removed from the Release Drafter configuration eventually.

Use Dependabot's `dependencies` label for Release Drafter

---

.github/workflows/reset-instance.yml

These references are misleading in the instance, as they are linked
to the instance repository instead of the cookiecutter repository, where
the PR was created.

Strip PR reference in Reset Instance workflow

---

{{cookiecutter.project_name}}/CODE_OF_CONDUCT.rst
{{cookiecutter.project_name}}/CONTRIBUTING.md
{{cookiecutter.project_name}}/docs/CODE_OF_CONDUCT.md
{{cookiecutter.project_name}}/docs/codeofconduct.rst
{{cookiecutter.project_name}}/docs/index.rst

* Generate CODE_OF_CONDUCT.rst using Pandoc
* Clean up generated markup in CODE_OF_CONDUCT.rst
* Add docs/codeofconduct.rst wrapper
* Use docs/codeofconduct.rst in master toctree
* Remove docs/CODE_OF_CONDUCT.md
* Remove CODE_OF_CONDUCT.md
* Adapt CoC link in Contributor Guide
cjolowicz/cookiecutter-hypermodern-python-instance#99

Convert Code of Conduct to reStructuredText

---

docs/conf.py
docs/guide.rst
{{cookiecutter.project_name}}/mypy.ini
{{cookiecutter.project_name}}/noxfile.py
{{cookiecutter.project_name}}/src/{{cookiecutter.package_name}}/__init__.py

Enable the strictness options associated with the `--strict` flag:
--warn-unused-configs
--disallow-any-generics
--disallow-subclassing-any
--disallow-untyped-calls
--disallow-untyped-defs
--disallow-incomplete-defs
--check-untyped-defs
--disallow-untyped-decorators
--no-implicit-optional
--warn-redundant-casts
--warn-unused-ignores
--warn-return-any
--no-implicit-reexport
--strict-equality
Also enable options for enhanced output:
--show-error-codes
--show-error-context
--show-column-numbers
--pretty
Fix some issues in the code base due to the increased strictness:
- Use `sys.version_info` instead of `try...except ImportError`
- Ignore missing imports for `importlib_metadata`.
- Allow untyped decorators in Nox sessions and test suite.
- Fix `[no-any-return]` in `Poetry.version`.
Closes …

Configure mypy to be strict and pretty

---

docs/guide.rst
{{cookiecutter.project_name}}/.pre-commit-config.yaml
{{cookiecutter.project_name}}/mypy.ini

This adds support for running mypy via pre-commit.
Closes #57 
Like flake8 and black, mypy is run via Poetry using a [local hook]. This has the drawback that you need to run `poetry install` before you can use pre-commit with your project. On other hand, it allows you to manage these tools as development dependencies in Poetry. The alternative would be to have duplicate and potentially diverging version pins in the Poetry lock file and the pre-commit configuration. Also, pinning subdependencies does not appear to be very practical with pre-commit.
[local hook]: https://pre-commit.com/#repository-local-hooks
Set [mypy_path] in the configuration file pointing it to the `src` directory. This is required to avoid errors about missing imports related to your package when mypy is invoked on …

Add pre-commit hook for mypy

---

{{cookiecutter.project_name}}/poetry.lock

cjolowicz/cookiecutter-hypermodern-python-instance#102
Bumps [virtualenv](https://github.com/pypa/virtualenv) from 20.0.17 to 20.0.18.
- [Release notes](https://github.com/pypa/virtualenv/releases)
- [Changelog](https://github.com/pypa/virtualenv/blob/master/docs/changelog.rst)
- [Commits](https://github.com/pypa/virtualenv/compare/20.0.17...20.0.18)
Signed-off-by: dependabot-preview[bot] <support@dependabot.com>
Co-authored-by: dependabot-preview[bot] <27856297+dependabot-preview[bot]@users.noreply.github.com>

Bump virtualenv from 20.0.17 to 20.0.18

---

{{cookiecutter.project_name}}/poetry.lock

cjolowicz/cookiecutter-hypermodern-python-instance#103
Bumps [urllib3](https://github.com/urllib3/urllib3) from 1.25.8 to 1.25.9.
- [Release notes](https://github.com/urllib3/urllib3/releases)
- [Changelog](https://github.com/urllib3/urllib3/blob/master/CHANGES.rst)
- [Commits](https://github.com/urllib3/urllib3/compare/1.25.8...1.25.9)
Signed-off-by: dependabot-preview[bot] <support@dependabot.com>
Co-authored-by: dependabot-preview[bot] <27856297+dependabot-preview[bot]@users.noreply.github.com>

Bump urllib3 from 1.25.8 to 1.25.9

---

docs/guide.rst
{{cookiecutter.project_name}}/.flake8
{{cookiecutter.project_name}}/noxfile.py
{{cookiecutter.project_name}}/poetry.lock
{{cookiecutter.project_name}}/pyproject.toml

Closes #51 
mypy is now configured with `disallow_untyped_defs`, so this extension appears to be not needed anymore.

Remove flake8-annotations

---

docs/guide.rst
{{cookiecutter.project_name}}/mypy.ini
{{cookiecutter.project_name}}/noxfile.py

Distribute inline type information using the `py.typed` marker file ([PEP 561]).
[pep 561]: https://www.python.org/dev/peps/pep-0561/
This allows us to remove `mypy_path` from mypy.ini.
Install the package into the Nox session for mypy. This is required to allow type-checking the test suite (when not also type-checking the package itself).
* Add py.typed marker file (PEP 561)
* Remove mypy_path from mypy.ini
This is no longer needed because the installed package contains the py.typed
marker file (PEP 561), allowing mypy to access inline type information. If an
import is followed from a module located outside of the package, mypy no longer
needs MYPY_PATH to be able to extract type information from the package. The
only requirement is that our package must be installed into the environment …

Add py.typed marker file (PEP 561)

---

.github/workflows/docs.yml
.github/workflows/tests.yml
{{cookiecutter.project_name}}/.github/workflows/coverage.yml
{{cookiecutter.project_name}}/.github/workflows/docs.yml
{{cookiecutter.project_name}}/.github/workflows/release.yml
{{cookiecutter.project_name}}/.github/workflows/test-pypi.yml
{{cookiecutter.project_name}}/.github/workflows/tests.yml

There is no need to specify `architecture: x64` for [actions/setup-python]. `x64` is the default architecture.
[actions/setup-python]: https://github.com/actions/setup-python

Omit redundant architecture for setup-python action

---

docs/guide.rst
{{cookiecutter.project_name}}/mypy.ini
{{cookiecutter.project_name}}/poetry.lock
{{cookiecutter.project_name}}/pyproject.toml
{{cookiecutter.project_name}}/src/{{cookiecutter.package_name}}/__init__.py
{{cookiecutter.project_name}}/src/{{cookiecutter.package_name}}/__main__.py

There is no need to define `__version__` up front. Users have `importlib.metadata` if they need the version number.
Remove dependency on `importlib-metadata`, which is no longer needed.
By default, click.version_option determines the version using the installed package metadata. This is precisely where we get out `__version__` from, so there is no point passing it to version_option explicitly.
See https://hynek.me/articles/packaging-metadata/
cjolowicz/cookiecutter-hypermodern-python-instance#112

Remove __version__ and importlib_metadata

---

{{cookiecutter.project_name}}/noxfile.py

Poetry.export uses tempfile.NamedTemporaryFile to create a temporary
requirements file, passing the name of the temporary file to `poetry export` via
its `--output` option.
Unfortunately, this does not work on Windows. On Windows NT and later, the name
attribute of the file-like object returned by tempfile.NamedTemporaryFile cannot
be used to open the file a second time, while the named temporary file is still
open.
https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile
Instead, use tempfile.TemporaryDirectory to create a temporary directory, and
store a file named `requirements.txt` in that directory. This technique should
be both secure and portable.
cjolowicz/cookiecutter-hypermodern-python-instance#117

Fix tempfile usage in Poetry.export on Windows

---

docs/guide.rst
{{cookiecutter.project_name}}/.gitattributes

This setting converts line endings to UNIX-style (`LF`), whenever text files are checked into and out of the repository.
Without this setting, the pre-commit hook for Prettier fails on the Windows runner. GitHub Actions configures git with `core.autocrlf = true`, because this is the default setting in Git for Windows.
https://prettier.io/docs/en/options.html#end-of-line
https://github.com/actions/checkout/issues/135

Enable end-of-line normalization with Git attributes

---

.github/workflows/tests.yml

On Windows, use `git add --renormalize .` after `git add .` to work around https://github.com/cookiecutter/cookiecutter/issues/405. Also switch to `$ErrorActionPreference = Continue` before invoking `git add .`. This command completes with an exit status of 1, and produces the warning "CRLF will be replaced by LF" for every file in the repository.

Run the Tests workflow on Windows and macOS (Cookiecutter)

---

docs/conf.py

Among other things, this sets the html lang attribute. With automatic
hyphenation, this ensures that the hyphenation rules for the correct
language are used (and that hyphenation occurs at all).

Configure Sphinx language to "en"

---

docs/guide.rst
{{cookiecutter.project_name}}/.pre-commit-config.yaml
{{cookiecutter.project_name}}/poetry.lock
{{cookiecutter.project_name}}/pyproject.toml

Use the official pre-commit hooks for flake8, black, and reorder-python-imports, instead of repository-local hooks. Add Flake8 plugins as additional dependencies to the flake8 hook.
Removing the Nox sessions and Poetry dependencies is left to follow-up PRs.

Use official pre-commit hooks instead of repository-local hooks

---

docs/guide.rst
{{cookiecutter.project_name}}/.pre-commit-config.yaml

The repository-local hook is problematic because it means that pre-commit needs to be able to run Poetry with a valid environment, introducing complexity and hidden dependencies.
The [official pre-commit] hook for mypy uses `--ignore-missing-imports` because it runs `mypy`
from an isolated virtualenv where imports for the dependencies are not accessible.
[official pre-commit]: https://github.com/pre-commit/mirrors-mypy
Running mypy from Nox means we can easily support multiple Python versions. This is
also possible with pre-commit, but leads to a lot of boilerplate.

Remove pre-commit hook for mypy

---

docs/guide.rst
{{cookiecutter.project_name}}/noxfile.py
{{cookiecutter.project_name}}/poetry.lock
{{cookiecutter.project_name}}/pyproject.toml

Remove the Nox session for Black, and remove its development dependency from Poetry. Black is now run as a pre-commit hook, so these are no longer useful.

Remove Nox session for Black

---

docs/guide.rst
{{cookiecutter.project_name}}/.github/workflows/release.yml
{{cookiecutter.project_name}}/.github/workflows/tests.yml
{{cookiecutter.project_name}}/noxfile.py

Run pre-commit as a part of both local and CI checks, using Nox as a single entry point. This PR adds pre-commit to the default Nox sessions, and enables caching in the Tests and Release workflows.

Run pre-commit from Nox and Tests workflow

---

README.rst
docs/guide.rst

This is an extensive overhaul of the documentation. Many sections have been improved, rewritten, or rearranged.
Originally, this was prompted by the different role of pre-commit. pre-commit is now a first-class citizen of the project template.
- Linting is entirely the responsibility of pre-commit, not Nox.
- pre-commit is run from Nox.
- Black and Flake8 have been moved from Poetry/Nox to pre-commit.

Update and rework the documentation

---

{{cookiecutter.project_name}}/noxfile.py

Install our package into the Nox session for mypy. mypy needs access to inline type information from our package (and potentially from its core dependencies, if they distribute types).
This fixes invocations like `nox -s mypy -- tests/test_main.py`. If the package is also passed to mypy, the bug is not triggered, because then mypy can access the types from the source tree. So `nox -s mypy` does not manifest the bug, for example, neither does CI.
Closes #242

Fix missing type information in mypy session

---

.pre-commit-config.yaml
{{cookiecutter.project_name}}/.pre-commit-config.yaml

- [changelog]
[changelog]: https://github.com/pre-commit/pre-commit-hooks/blob/master/CHANGELOG.md#300---2020-05-14

Bump pre-commit-hooks from v2.5.0 to v3.0.0

---

.github/workflows/reset-instance.yml

Generating the project from the local checkout is problematic because it
writes the relative path to the template directory to .cookiecutter.json,
instead of the template URL.
This appears to work when there is already a checkout of the template
because `_template` contains the template name. But it breaks when you
try to use `cookiecutter --checkout` with the template, for example from
my patched version of cupper.
Closes #288

Fix template URL in Reset Instance workflow

---

CONTRIBUTING.rst
docs/contributing.rst
{{cookiecutter.project_name}}/CONTRIBUTING.rst
{{cookiecutter.project_name}}/README.rst
{{cookiecutter.project_name}}/docs/contributing.rst
{{cookiecutter.project_name}}/docs/index.rst

Add the following sections to the generated README.rst:
- Features (empty)
- Requirements (empty)
- Installation
- Usage (empty)
- Contributing
- License
- Issues
- Credits
The structure is based on @hackebrot's cookiecutter-pytest-plugin.
Closes #205 
Closes #284

Expand generated README.rst

---

{{cookiecutter.project_name}}/.github/workflows/tests.yml

This PR refactors the Tests workflow, without affecting check outcomes.
- Provide names for jobs and steps (see #178)
- Print versions of tools installed by pip (see #270)
- Do not inline lists
- Add blank lines between steps
- Add blank lines between top-level keys
- Name cleanup for the `pre-commit-cache` step ID (was: `cache_key_prefix`)
Closes #270

Refactor the Tests workflow

---

docs/_static/custom.css
docs/index.rst

Links in the first paragraph of every section are not underlined. This is because the CSS selector intended for badges (#297) matches these links erroneously.
Precede the badges by an `.. rst-class:: badges` directive. This wraps them in an HTML element with the badges class, which can easily be targeted in CSS.
```html
<p class="badges>
...
</p>
```
Closes #302

Fix missing underlines on some links

---

docs/guide.rst
{{cookiecutter.project_name}}/noxfile.py
{{cookiecutter.project_name}}/poetry.lock
{{cookiecutter.project_name}}/pyproject.toml

Run Coverage.py directly instead of via the pytest plugin.
The main reasons for this removal is that it reduces complexity by removing a layer of indirection. We don't need the plugin, and I prefer a slightly longer, but more explicit session definition.
Another reason for the removal is that this makes it easier to move coverage reporting into a separate Nox session. Nox itself does this, and uses `session.notify` to report after the test suite. This may also be useful for Codecov integration in the Tests workflow. All of this requires some more research though.
Closes #305

Remove pytest-cov

---

{{cookiecutter.project_name}}/.github/workflows/tests.yml

Only restore the pre-commit cache if the job runs the pre-commit session. Previously, the pre-commit cache was restored in all non-Windows jobs, even when the Nox session was not running pre-commit.

Do not restore pre-commit cache in non-pre-commit jobs

---

{{cookiecutter.project_name}}/noxfile.py

In `tool.coverage.paths.source`, the following paths are specified as equivalent:
- `src`
- `*/site-packages`
Since tests run against the installed package, the report displays the second, longer path prefix. But we can get coverage reports to use the shorter first form by processing coverage data with `coverage combine`. And for that, we need to run coverage with `--parallel`.
See https://hynek.me/articles/testing-packaging/

Remove */site-packages path prefix from coverage report

---

docs/guide.rst

pre-commit is only run with Python 3.8. The table of Nox sessions in the documentation lists all supported Python versions.

Fix documented Python versions for pre-commit session

---

{{cookiecutter.project_name}}/.github/workflows/tests.yml

The mypy and tests jobs were running with any Python version installed on the runner. If a registered Python version for the session was not installed on the runner, they would print a message that the session was skipped.
Avoid all of this, and specifically run the session for the targeted Python version (as specified in `matrix.python-version`).

Only run the targeted Python version in each CI job

---

docs/guide.rst
{{cookiecutter.project_name}}/noxfile.py

Produce a single combined coverage report for all Python versions, at the end of the Nox run. Adds a Nox session `coverage`, which is triggered by the `tests` sessions to run once after completion.

Produce a single combined coverage report for all Python versions

---

docs/guide.rst
{{cookiecutter.project_name}}/noxfile.py

Do not combine coverage data when the coverage session is invoked with
arguments, or when there are no data files to be combined.
Combining coverage data is only possible when there are unprocessed
coverage files, such as when triggered by the tests session. This makes
it impossible to use the coverage session on its own. Use cases for that
include the following:
- Creating an XML coverage report for Codecov during CI
- Interacting with `coverage` directly during development
Note that this change means that the coverage session is not strictly
idempotent:
- If there are unprocessed data files, the session combines the files,
erasing the existing data (and removing the files).
- If there are no unprocessed data files, the session simply displays
the existing data.
This behavior appears …

Allow coverage session to be run stand-alone

---

docs/guide.rst
{{cookiecutter.project_name}}/.github/workflows/coverage.yml

The Coverage workflow was broken by the removal of pytest-cov in #305. This PR adapts the Coverage workflow to use the new coverage session introduced in #312 and #315. This is an interim change before merging the Coverage workflow into the Tests workflow.

Adapt Coverage workflow to use coverage session

---

docs/guide.rst
{{cookiecutter.project_name}}/.github/workflows/constraints.txt

virtualenv uses the bundled pip by default. As a result, Nox sessions do not use the pip specified in our constraints file. This change pins virtualenv to the latest version, which bundles the latest pip at the time of the virtualenv release. virtualenv releases are timed to occur in a small time window after pip releases.
Note that Nox sessions continue to use the bundled pip instead of the one specified in the constraints file, so the real problem is not addressed. I first thought that this would require Nox to expose virtualenv's `--pip` option. But it appears that you can also pass the pip version to virtualenv using the `VIRTUALENV_PIP` environment variable. Alas, this will mean boilerplate in the workflow definition, and/or a duplication of the pip version from constraints.txt.
See …

Pin virtualenv to 20.0.21

---

{{cookiecutter.project_name}}/mypy.ini
{{cookiecutter.project_name}}/noxfile.py

Use the [--python-executable] option to mypy to point the type checker to the Python installation running Nox, rather than the virtual environment of the Nox session, when type-checking `noxfile.py` itself. This allows mypy to find the type information for Nox, without having to install Nox into the session. Nox distributes type information inline and declares this fact using the py.typed file specified in [PEP 561].
[--python-executable]: https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-python-executable
[PEP 561]: https://www.python.org/dev/peps/pep-0561/
Note that this check is somewhat indeterministic in local testing. The Nox version is only pinned in CI. For users with a pre-2020.5.24 version of Nox, the session will fail due to missing type hints. The session …

Type-check noxfile.py

---

docs/guide.rst

Update the Python 3.8 references in the User Guide section about setting up Python with pyenv, bumping from 3.8.2 to 3.8.3.

Update documentation for Python 3.8.3

---

{{cookiecutter.project_name}}/README.rst
{{cookiecutter.project_name}}/docs/reference.rst

The files `README.rst` and `reference.rst` start with a blank line, due to a Jinja macro definition at the top of these files. Eliminate the blank line by ending the macro definition with `-%}`.
Closes #350

Fix leading blank line in README and API reference

---

docs/guide.rst
{{cookiecutter.project_name}}/.github/workflows/tests.yml
{{cookiecutter.project_name}}/noxfile.py

- Add typeguard session to the default Nox sessions
- Add typeguard session to the Tests workflow

Enable runtime type-checking with Typeguard by default

---

README.rst

The development status of this Cookiecutter template is Alpha:
- It does not contain all the features that are planned for the final version.
- The overall design may change in significant ways.
- The project is not recommended for production use at this time.
Closes #377

Add badge with development status alpha

---

README.rst
{{cookiecutter.project_name}}/README.rst

* Added the second option you suggested (with Read the docs on a separate row).
* Reordered links to follow same order than are shown.
* Changed Read the docs badge to the one used in https://github.com/dateutil/dateutil/blob/fc9b1625ebc729f01e449879b6b140abd12ae621/README.rst
* Also changed the README.md from the cookiecutter using very similar logic.
Closes #403

Organize badges in multiple rows

---

docs/guide.rst

Update the pyenv section in the User Guide to the latest Python versions in the 3.6 and 3.7 release series.

Update documentation for Python 3.7.8 and 3.6.11

---

docs/guide.rst
{{cookiecutter.project_name}}/.pre-commit-config.yaml
{{cookiecutter.project_name}}/noxfile.py
{{cookiecutter.project_name}}/poetry.lock
{{cookiecutter.project_name}}/pyproject.toml

This PR changes the way [pre-commit] is integrated with projects. Python-language hooks are no longer managed by pre-commit. Instead, they are tracked as development dependencies in Poetry, and installed into the Nox session alongside pre-commit itself. As development dependencies, they are also present in the Poetry environment.
[pre-commit]: https://pre-commit.com/
In detail, this includes the following changes:
- Python-language hooks are converted to [repository-local]¹ [system hooks]².
- Hook dependencies are added to Poetry.
- Hook dependencies are installed into the Nox session for pre-commit.
[repository-local]: https://pre-commit.com/#repository-local-hooks
[system hooks]: https://pre-commit.com/#system
¹ *Repository-local hooks* are not backed by an external git repository.
² …

Track pre-commit hooks as Poetry dependencies

---

docs/guide.rst

Instead of advertising a bimonthly release cadence with the proviso that initial releases may occur more frequently, advertise the de-facto release cadence we have had ever since the initial release (2020.3.27), which is monthly.

Advertise a monthly release cadence

---

{{cookiecutter.project_name}}/mypy.ini

Sort the `[mypy-<package>]` sections in `mypy.ini` alphabetically. It is common to have many of these, for example to ignore missing imports in third-party dependencies, so sorting makes the file more maintainable.

Reorder sections in mypy.ini

---

{{cookiecutter.project_name}}/noxfile.py

Closes #470
- Return the basename of the wheel from `Poetry.build`
- Locate wheel using Poetry's output when installing
- Remove unused function `Poetry.version`

Fix package installation in Nox sessions with non-final release versions

---

CONTRIBUTING.rst
{{cookiecutter.project_name}}/CONTRIBUTING.rst

As discussed in #471 current documentation is referencing a nox black session.
This is no more used. Reference is removed in cookiecutter-hypermoern-python project and replace by explanation how to install the pre-commit hook for the project template.
fix #471

Remove black nox session from documentation

---

{{cookiecutter.project_name}}/noxfile.py

The `--no-root` option of Poetry's install command allows installing core dependencies without the package itself, so it is no longer necessary to export requirements and install with pip.

Use Poetry to install core dependencies in Nox sessions

---

{{cookiecutter.project_name}}/noxfile.py

This PR speeds up Nox runs by exporting requirements only when the lock file changes. The requirement files are cached in the per-session temporary directory introduced in Nox 2020.5.24. As a consequence, requirements are only reused as long as the Nox environments are reused (`--reuse-existing-virtualenvs`).
As a side effect, the requirements file for `safety` is no longer generated without hashes. `safety` appears to handle requirements files with hashes just fine.

Cache exported requirements in Nox sessions

---

{{cookiecutter.project_name}}/.flake8

Disable the following [flake8-rst-docstrings] warnings:
- `RST203` Definition list ends without a blank line; unexpected unindent.
- `RST301` Unexpected indentation
These warnings are commonly caused by multi-line parameter descriptions in Google-style docstrings.
[flake8-rst-docstrings]: https://github.com/peterjc/flake8-rst-docstrings
Closes #497 
See https://github.com/peterjc/flake8-rst-docstrings/issues/17
**Examples**
```python
def add(a: int, b: int) -> int:
"""Add two integers.
Args:
a: This is a multi-line parameter description for
the parameter named ``a``.
b: This is just a single line.
Returns:
The sum of ``a`` and ``b``.
"""
return a + b
```
```python
def add(a: int, b: int) -> int:
"""Add two integers.
Args:
a: This is just a single line.
b: This is a multi-line parameter …
```

Ignore flake8-rst-docstrings warnings for multi-line parameter descriptions

---

.github/workflows/constraints.txt
.github/workflows/tests.yml
CONTRIBUTING.rst
README.rst
docs/guide.rst
{{cookiecutter.project_name}}/.github/workflows/constraints.txt
{{cookiecutter.project_name}}/.github/workflows/tests.yml
{{cookiecutter.project_name}}/CONTRIBUTING.rst
{{cookiecutter.project_name}}/noxfile.py

This PR adds [nox-poetry], a spinoff of this project, as a global dependency. This package replaces the boilerplate that was previously injected into the `noxfile.py` of generated projects to integrate Nox and Poetry. 
Having this on PyPI means this glue code no longer needs to be copied into every project, and users can receive bugfixes in a normal way, without the hassle of updating their project from the template. Also, moving this into a separate package made it possible to provide a much better integration of Poetry and Nox than a bunch of functions in `noxfile.py` were able to. With nox-poetry, users can write Nox sessions just as they would with a setuptools-based project; only a single import at the top of the file is required.
There are also some drawbacks, which should be named …

Add nox-poetry

---

{{cookiecutter.project_name}}/mypy.ini
{{cookiecutter.project_name}}/noxfile.py

The [pytest 6.0.0] release added support for static typing, with types distributed inline with the package (as per [PEP 561]).
This PR removes the following pytest-related exceptions from `mypy.ini`:
- Remove `ignore_missing_imports` for `pytest`
- Remove `allow_untyped_decorators` for `tests`
For this to work, we also need to install pytest into the Nox session for mypy. This allows mypy to access the type information distributed with pytest.
Closes #552
[pytest 6.0.0]: https://docs.pytest.org/en/latest/changelog.html#pytest-6-0-0rc1-2020-07-08
[pep 561]: https://www.python.org/dev/peps/pep-0561/

Do not ignore missing type imports from pytest

---

{{cookiecutter.project_name}}/.flake8

This warning is triggered when a multi-line parameter description is surrounded by other parameters.
Closes #569 
See https://github.com/peterjc/flake8-rst-docstrings/issues/17 for details

Ignore RST201 for compatibility with Google-style docstrings

---

docs/guide.rst
{{cookiecutter.project_name}}/.github/workflows/tests.yml
{{cookiecutter.project_name}}/noxfile.py

- In `tests` nox session, `coverage` session is automatically called only in interactive mode.
- In `tests` GA workflow, coverage data are saved as artefact for each entry in the matrix.
- In `tests` GA workflow, a `coverage`job is added to download from artefacts all coverage data, combine them and upload the report on codecov.
- Documentation update.
Closes #468

Combine coverage data with GitHub Action

---

{{cookiecutter.project_name}}/.github/workflows/tests.yml

Due to an oversight when merging #568 , `nox-poetry` (added in #570) was not installed in the new `coverage` job, leading to a `ModuleNotFoundError` during workflow runs (see https://github.com/cjolowicz/cookiecutter-hypermodern-python-instance/runs/1228484769).

Fix missing nox-poetry in Tests workflow

---

{{cookiecutter.project_name}}/.github/workflows/release.yml

The Release workflow now supports both `main` and `master` as names for the default repository branch. Since October 1, 2020, new GitHub repositories are created using `main` as the default branch name. See https://github.com/github/renaming for details.
We continue to support the legacy name `master` for now. This allows existing projects to receive changes from the template, without requiring them to migrate their default branch beforehand.
Closes #561

Support `main` branch in Release workflow

---

docs/guide.rst
{{cookiecutter.project_name}}/docs/conf.py
{{cookiecutter.project_name}}/docs/requirements.txt
{{cookiecutter.project_name}}/noxfile.py
{{cookiecutter.project_name}}/poetry.lock
{{cookiecutter.project_name}}/pyproject.toml

Configure Sphinx to use the Read the Docs theme.
This fixes a discrepancy between documentation builds on Read the Docs on one side (which use sphinx-rtd-theme by default), and builds on GitHub Actions and local builds on the other side (which default to Alabaster). As the documentation is hosted with Read the Docs, the discrepancy is resolved in favor of sphinx-rtd-theme, avoiding a breaking change.
Closes #564

Use Read the Docs theme in local builds

---

README.rst
docs/guide.rst
{{cookiecutter.project_name}}/.github/workflows/release.yml
{{cookiecutter.project_name}}/.github/workflows/tests.yml
{{cookiecutter.project_name}}/noxfile.py
{{cookiecutter.project_name}}/pyproject.toml

This PR adds support for Python 3.9.
Closes #14 
- Add trove classifier for Python 3.9.
- Add Python 3.9 support to `mypy`, `tests`, `typeguard`, and `xdoctest`
- Replace Python 3.8 by Python 3.9 in `pre-commit` and `safety`
- Keep Python 3.8 for `docs` and `docs-build` pending https://github.com/readthedocs/readthedocs.org/issues/7554
- The `coverage` session does not use a specific Python version.
- Replace Python 3.8 by Python 3.9 in the Release workflow.
Support Python 3.9 in these jobs:
- tests / mypy
- tests / tests
Replace Python 3.8 by 3.9 in these jobs:
- coverage
- tests / pre-commit
- tests / safety
- tests / tests (Windows)
- tests / tests (Mac)
- tests / typeguard
Keep Python 3.8 in this job (see above):
- tests / docs-build
(The runner OS is Ubuntu unless noted otherwise.)

Support Python 3.9

---

docs/guide.rst
{{cookiecutter.project_name}}/.github/workflows/tests.yml
{{cookiecutter.project_name}}/noxfile.py

This PR includes the Nox session for [xdoctest] in local checks and in the Tests workflow. Previously, the session had to be enabled explicitly using the `--session` option, and wasn't run in CI at all. The session runs locally for all supported major Python versions, and on Python 3.9 during CI.
Closes #251 
[xdoctest]: https://xdoctest.readthedocs.io/en/latest/

Enable Nox session for xdoctest by default

---

docs/guide.rst

In the User Guide, the table listing the direct dependencies of generated projects was missing several packages.
Also, update the URL of `sphinx-autobuild` to its new location.

Fix incomplete dependencies table in User Guide

---

CONTRIBUTING.rst
README.rst
docs/guide.rst

Remove references to master branch from documentation

---

.pre-commit-config.yaml
{{cookiecutter.project_name}}/.pre-commit-config.yaml

[Prettier has moved its pre-commit support](https://github.com/prettier/prettier/pull/8937) to [github.com/prettier/pre-commit](https://github.com/prettier/pre-commit).
Drafting this PR to also test if it will fix the failing actions on Windows.
Closes #640

Update prettier hook to new pre-commit repo

---

{{cookiecutter.project_name}}/pyproject.toml

The `[build-system]` section of `pyproject.toml` can be changed as of Poetry >= 1.1.0 to be a standalone backend. This updates the section to the recommended build backend to poetry-core.
More details in Poetry's [announcement](https://python-poetry.org/blog/announcing-poetry-1-1-0.html) and the [poetry-core](https://github.com/python-poetry/poetry-core) project.
---
Closes #635

Change to standalone build backend  (PEP-517)

---

docs/guide.rst

Upgrade Ubuntu version in Windows Subsystem for Linux section of the guide to 20.04. We might consider just leaving the version out of the guide to prevent it from needing to be periodically upgraded.
Closes #613

Upgrade Ubuntu version in guide

---

{{cookiecutter.project_name}}/pyproject.toml

if the package name and project name are not similar (more than `-` replaced by `_`), a `package` key will be added in `pyproject.toml` file.
Example: 
```toml
packages = [
{ include = "package_name", from = "src" },
]
```
fix: #546

Support packages whose name does not match the project name

---

README.rst
docs/guide.rst
docs/index.rst

This section highlights the main changes brought by this release.
- **Manage GitHub labels using a YAML configuration file** (thanks @oncleben31)
GitHub labels can now be managed using the `.github/labels.yml` configuration file, using the [GitHub Labeler] action. Labels are used, among other things, to categorize pull requests for the release notes. Thanks to the new Labeler workflow, it is no longer necessary to create GitHub labels manually after generating a project.
[GitHub Labeler]: https://github.com/marketplace/actions/github-labeler
- **Support packages whose name does not match the project name** (thanks @oncleben31)
By default, Poetry only includes packages if their name matches the configured project name. If a custom `package_name` is specified on project generation, the …

Release 2020.11.15

---

noxfile.py
tools/prepare-github-release.py
tools/publish-github-release.py

The intended workflow is as follows:
```sh
export GITHUB_TOKEN=<secret>
nox -rs prepare-release
nox -rs publish-release
```
Releases require some changes to the documentation, and we always hand-edit the draft release before publishing. So we cannot release the Cookiecutter simply by publishing the automated draft release. Instead, the `prepare-release` session creates a PR with all required changes, and copies the release notes from the draft release into the pull request description. The `publish-release` session merges the PR, copies the release notes back into the draft release, and publishes the release.
There is a race condition with Release Drafter here, which will also attempt to update the draft release when the PR is merged. Unfortunately, there is no obvious way to skip the …

Add tools to automate Cookiecutter releases

---

README.rst
docs/guide.rst
docs/index.rst
docs/quickstart.rst

This is a maintenance release.
* Bump actions/download-artifact from v2.0.5 to v2.0.6 (#680) @cjolowicz
* Bump actions/download-artifact from v2.0.6 to v2.0.8 (#727) @cjolowicz
* Bump actions/setup-python from v2.1.4 to v2.2.1 (#748) @cjolowicz
* Bump actions/upload-artifact from v2.2.0 to v2.2.1 (#681) @cjolowicz
* Bump actions/upload-artifact from v2.2.1 to v2.2.2 (#752) @cjolowicz
* Bump codecov/codecov-action from v1.0.14 to v1.0.15 (#682) @cjolowicz
* Bump codecov/codecov-action from v1.0.15 to v1.2.1 (#725) @cjolowicz
* Bump coverage from 5.3 to 5.3.1 (#743) @cjolowicz
* Bump coverage from 5.3.1 to 5.4 (#744) @cjolowicz
* Bump crazy-max/ghaction-github-labeler from v3.1.0 to v3.1.1 (#704) @cjolowicz
* Bump darglint from 1.5.5 …

Release 2021.1.29

---

{{cookiecutter.project_name}}/noxfile.py

- Use `@session` decorator from nox-poetry instead of nox.
- Remove uses of deprecated functions `nox_poetry.patch` and `nox_poetry.export_requirements`.
- Disable mypy warning `[attr-defined]` when accessing `session._runner`, which is a private attribute and therefore missing from the type stubs provided by nox-poetry. We use this attribute to determine the number of sessions enabled for the Nox run.

Use session decorator from nox-poetry

---

{{cookiecutter.project_name}}/README.rst

Switch the Codecov badge to GitHub's new default branch `main`.

Fix reference to master in Codecov link on README

---

tools/prepare-github-release.py

Now that this repository has switched to the `main` branch, change the defaults in the release automation tools accordingly.

Default to main branch in release tool

---

{{cookiecutter.project_name}}/noxfile.py

This reverts commit 8688123d9981926d8811c438e4e67bec431adf7f.
The CVE has been revoked.

Revert "Ignore CVE-2020-28476 affecting all versions of tornado (#763)"

---

README.rst
docs/guide.rst
docs/index.rst
docs/quickstart.rst

This release allows generated projects to choose a license. Supported licenses are MIT, Apache-2.0, and GPL-3.0.
* Add license parameter (#701) @paw-lu
* Use session decorator from nox-poetry (#769) @cjolowicz
* Fix reference to master in Codecov link on README (#788) @cjolowicz
* Bump actions/cache from v2.1.3 to v2.1.4 (#780) @cjolowicz
* Bump codecov/codecov-action from v1.2.1 to v1.2.2 (#815) @cjolowicz
* Bump darglint from 1.5.8 to 1.6.0 (#783) @cjolowicz
* Bump darglint from 1.6.0 to 1.7.0 (#810) @cjolowicz
* Bump flake8-bugbear from 20.11.1 to 21.3.2 (#808) @cjolowicz
* Bump jinja2 from 2.11.2 to 2.11.3 (#801) @cjolowicz
* Bump mypy from 0.800 to 0.812 (#807) @cjolowicz
* Bump nox-poetry from 0.7.1 to 0.8.1 in …

Release 2021.3.14

---

.github/workflows/docs.yml
CONTRIBUTING.rst
docs/conf.py
docs/guide.rst
noxfile.py

The cookiecutter documentation is very complete and is full of external links.
I suggest to add a nox session and a GitHub workflow to check if there is no dead links in the documentation.
According to your feedback we could add it in the template too.

Check for dead links in documentation

---

{{cookiecutter.project_name}}/poetry.lock

* Bump gitdb from 4.0.5 to 4.0.7
* Bump identify from 2.1.1 to 2.2.3
* Bump nodeenv from 1.5.0 to 1.6.0
* Bump pydocstyle from 5.1.1 to 6.0.0
* Bump pyflakes from 2.3.0 to 2.3.1
* Bump regex from 2020.11.13 to 2021.4.4
* Bump ruamel.yaml from 0.16.13 to 0.17.4
* Bump smmap from 3.0.5 to 4.0.0
* Bump typed-ast from 1.4.2 to 1.4.3

Upgrade subdependencies

---

.github/workflows/reset-instance.yml
README.rst

Update the "Reset Instance" workflow and the badges to point to the new default branch of https://github.com/cjolowicz/cookiecutter-hypermodern-python-instance.

Switch instance repository to main branch

---

{{cookiecutter.project_name}}/.darglint

Closes #793 
The current setting of `short` is too strict and discourages from writing long
docstrings when it does not make sense to include the full function signature
boilerplate, for example in internal APIs with self-explanatory signatures.

Configure darglint to allow long docstrings without signatures

---

{{cookiecutter.project_name}}/noxfile.py

Closes #818 
Invoke safety with the `--full-report` option, to provide additional information, such as the Safety DB identifier and the affected version ranges. Previously, the safety session used `--bare` which prints only the names of vulnerable packages.

Print full report in safety session

---

{{cookiecutter.project_name}}/.flake8

Closes #794 
This PR configures [flake8-rst-docstrings] to recognize some common [Sphinx roles] and [directives]:
[flake8-rst-docstrings]: https://github.com/peterjc/flake8-rst-docstrings
[Sphinx roles]: https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html
[directives]: https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-deprecated
- class
- const
- func
- meth
- mod
- ref
- deprecated

Configure flake8-rst-docstrings for Sphinx

---

README.rst
docs/conf.py
docs/guide.rst
docs/index.rst
docs/quickstart.rst

This release contains various minor improvements to automated checks.
* Configure darglint to allow long docstrings without signatures (#871) @cjolowicz
* Configure flake8-rst-docstrings for Sphinx (#876) @cjolowicz
* Print full report in safety session (#872) @cjolowicz
* Simplify mypy.ini using the strict setting (#869) @cjolowicz
* Improve error message when nox-poetry is not installed (#875) @cjolowicz
* Bump actions/cache from v2.1.4 to v2.1.5 (#853) @cjolowicz
* Bump actions/download-artifact from v2.0.8 to v2.0.9 (#857) @cjolowicz
* Bump actions/setup-python from v2.2.1 to v2.2.2 (#866) @cjolowicz
* Bump actions/upload-artifact from v2.2.2 to v2.2.3 (#858) @cjolowicz
* Bump codecov/codecov-action from v1.2.2 to v1.3.1 (#833) …

Release 2021.4.15

---

docs/guide.rst

We're no longer using this setting in `mypy.ini`, since pytest now ships with types.

Remove obsolete note on `mypy --ignore-missing-imports` from User Guide

---

docs/guide.rst

A deep link into pip docs about editable installs was broken.

Fix broken link to pip docs in User Guide

---

{{cookiecutter.project_name}}/noxfile.py

This PR simplifies the handling of `posargs` in the Nox session for Coverage.py.
Pass empty `posargs` when scheduling the coverage sesseion via `session.notify`. This avoids invoking `coverage` with options intended for pytest. Previously, our solution relied on inspecting a private attribute of `nox.Session`.
The `posargs` parameter for `session.notify` was introduced in Nox 2021.6.6.
Use the `nox.needs_version` attribute to declare the dependency on Nox >= 2021.6.6.
Note: This requires nox-poetry 0.8.6 to avoid an error from mypy.

Simplify Nox session for code coverage

---

docs/guide.rst
{{cookiecutter.project_name}}/mypy.ini
{{cookiecutter.project_name}}/pyproject.toml

Hey! Thanks for this dope `cookiecutter` template. Let me know if I need to make any changes before this can be merged.
❤️
<hr />
Closes #917

Move `mypy` configuration into `pyproject.toml`

---

README.rst
docs/guide.rst
docs/index.rst
docs/quickstart.rst

- Generated projects now have one configuration file less, as the mypy configuration was moved to the `pyproject.toml` file.
- Documentation is now built using Python 3.9, both on ReadTheDocs and locally.
- The `noxfile.py` now requires a recent version of Nox.
Read on for the complete list of changes.
* Move `mypy` configuration into `pyproject.toml` (#935) @yeskunall
* Update pre-commit hook for Prettier to new repository (#916) @staticdev
* Simplify Nox session for code coverage (#943) @cjolowicz
* Add per-machine coverage data files to `.gitignore` file (#886) @cjolowicz
* Use Python 3.9 when building on ReadTheDocs (#946) @cjolowicz
* Require click 8.x (#947) @staticdev
* Bump actions/cache from 2.1.5 to 2.1.6 (#923) @cjolowicz …

Release 2021.6.15

---

docs/guide.rst

mypy is configured via `pyproject.toml` now.
Follow-up to #935

Remove reference to mypy.ini from User Guide

---

{{cookiecutter.project_name}}/noxfile.py
{{cookiecutter.project_name}}/src/{{cookiecutter.package_name}}/__main__.py

click >= 8.0 ships with py.typed, so types-click is not required.
Installing types-click with click >= 8.0 leads to a mypy error, see python/typeshed#5642

Remove types-click from Nox session for mypy

---

README.rst
docs/guide.rst
docs/index.rst
docs/quickstart.rst

This release allows marking the development status (e.g. alpha, beta, stable) when generating a project. The development status is included in the package metadata and indicated by a badge in the README and documentation.
* Add Trove classifier for Development Status (#981) @cjolowicz
* Bump actions/download-artifact from 2.0.9 to 2.0.10 (#973) @cjolowicz
* Bump actions/upload-artifact from 2.2.3 to 2.2.4 (#974) @cjolowicz
* Bump mypy from 0.902 to 0.910 (#972) @cjolowicz
* Bump pep8-naming from 0.11.1 to 0.12.0 (#968) @cjolowicz
* Bump pip from 21.1.2 to 21.1.3 in /.github/workflows (#970) @cjolowicz
* Bump poetry from 1.1.6 to 1.1.7 in /.github/workflows (#971) @cjolowicz
* Bump sphinx from 4.0.2 to 4.1.1 (#975) @cjolowicz
* Bump …

Release 2021.7.15

---

{{cookiecutter.project_name}}/CONTRIBUTING.rst

Fix typo in CONTRIBUTING.rst

---

docs/guide.rst
{{cookiecutter.project_name}}/noxfile.py
{{cookiecutter.project_name}}/pyproject.toml

Fixes #985 
- 🔧 [mypy] Warn about unreachable code
- 🔧 [nox] Avoid warning about unreachable code

🔧 [mypy] Warn about unreachable code

---

.github/workflows/tests.yml

https://pythoninsider.blogspot.com/2021/10/python-3100-is-available.html
"3.10" must be quoted in yaml... https://dev.to/hugovk/the-python-3-1-problem-85g

GitHub Actions: Add Python 3.10 to the testing

---

README.rst
docs/guide.rst
docs/quickstart.rst
{{cookiecutter.project_name}}/.github/workflows/release.yml
{{cookiecutter.project_name}}/.github/workflows/tests.yml
{{cookiecutter.project_name}}/noxfile.py
{{cookiecutter.project_name}}/pyproject.toml

Fixes #580 
- 👷 [nox] Support Python 3.10
- 👷 [github] Use Python 3.10 in Tests workflow
- 👷 [github] Use Python 3.10 in Release workflow
- 📦 [poetry] Add Trove classifier for Python 3.10

Support Python 3.10

---

README.rst
docs/guide.rst
docs/index.rst
docs/quickstart.rst

- This release adds support for Python 3.10, while dropping support for Python 3.6
(EOL in December 2021).
- Poetry and Nox are now installed on GitHub Actions using pipx, in isolated environments.
- mypy is now configured to warn about unreachable code.
Read on for the full list of changes.
* Drop support for Python 3.6 (#1054) @cjolowicz
* Support Python 3.10 (#1052) @cjolowicz
* Install Poetry and Nox using pipx in Tests workflow (#1051) @cjolowicz
* [nox] Chain exception correctly (#1015) @oncleben31
* [mypy] Warn about unreachable code (#1025) @cjolowicz
* Fix typo in CONTRIBUTING.rst (#1010) @benjaminrose
* Bump actions/checkout from 2.3.4 to 2.4.0 (#1026) @cjolowicz
* Bump babel from 2.9.0 to 2.9.1 (#1023) @cjolowicz
* Bump …

Release 2021.11.8

---

.github/workflows/constraints.txt
.github/workflows/reset-instance.yml
.github/workflows/update-instance.yml

Use [cutty](https://github.com/cjolowicz/cutty) to update the Cookiecutter instance at [cjolowicz/cookiecutter-hypermodern-python-instance](https://github.com/cjolowicz/cookiecutter-hypermodern-python-instance). This will import `${GITHUB_SHA}` on every push to the main branch, and push the import commit to the instance.
- 👷 [github] Use Python 3.10 in Reset Instance workflow
- 👷 [github] Use cutty in Reset Instance workflow
- 👷 [github] Serialize workflow runs for Reset Instance
- 👷 [github] Rename workflow to "Update Instance"
See also:
- #757 
- #756 
- #429 
- #220

👷 [github] Use cutty to update the Cookiecutter instance

---

.github/workflows/update-instance.yml

This avoids the following error on GA, which I have not been able to reproduce locally:
```
Run pipx install --pip-args=--constraint=.github/workflows/constraints.txt cutty || cat /opt/pipx/logs/cmd_*_pip_errors.log
Fatal error from pip prevented installation. Full pip output in file:
/opt/pipx/logs/cmd_2021-11-09_13.43.30_pip_errors.log
creating virtual environment...
Some possibly relevant errors from pip install:
installing cutty...
ERROR: Cannot install cutty because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
Error installing cutty.
PIP STDOUT
----------
The conflict is caused by:
The user requested cutty
The user requested (constraint) cutty==0.16.0
To fix …
```

👷 [github] Use pip to install cutty in Reset Instance workflows

---

README.rst
docs/guide.rst
docs/index.rst
docs/quickstart.rst

This release upgrades the CI checks on Windows and macOS to Python 3.10.
* Release 2021.11.10 (cjolowicz/cookiecutter-hypermodern-python-instance#665) @cjolowicz
* 👷 [github] Use Python 3.10 on Windows and macOS in Tests workflow (cjolowicz/cookiecutter-hypermodern-python-instance#664) @cjolowicz
* ⬆ [poetry] Update dependencies (cjolowicz/cookiecutter-hypermodern-python-instance#663) @cjolowicz
* 👷 [github] Do not update instance with commits imported from it (#1061) @cjolowicz
* 👷 [github] Use pip to install cutty in Reset Instance workflows (#1060) @cjolowicz
* 👷 [github] Use cutty to update the Cookiecutter instance (#1059) @cjolowicz

Release 2021.11.10

---

README.rst
docs/guide.rst
noxfile.py
tools/dependencies-table.py

- ✨ [tools] Add tool for generating dependencies table in User Guide
- 👷 [nox] Add session `dependencies-table`
- 📚 [docs] Update dependency table in User Guide
- 📚 [README] Add pyupgrade to feature list
- 📚 [docs] Add pyupgrade to the list of pre-commit hooks
- 📚 [docs] Add documentation section for pyupgrade to User Guide

📚 Document pre-commit hook for pyupgrade

---

README.rst
docs/guide.rst
docs/index.rst
docs/quickstart.rst

Here are the major changes brought by this release:
- Add a pre-commit hook for [pyupgrade], a tool for upgrading your source code to newer versions of the Python language and standard library.
- Use the [furo] Sphinx theme for documentation. Furo is a clean customizable theme for technical documentation, with a focus on being responsive and easy to navigate and search.
- Include the test suite itself when measuring code coverage: tests are code. Read more about the reasons behind this on [Ned Batchelder's blog][coverage-blog].
- Enable color output on GitHub Actions for pytest, pre-commit, Sphinx, and xdoctest. Tools on GitHub Actions default to monochrome output, and every tool has its own convention for overriding this (if any). This was a fun ride.
[furo]: https://pradyunsg.me/furo/ …

Release 2021.11.26

---

README.rst
docs/guide.rst

- 📚 [README] Add isort to list of features
- 📚 [guide] Update table of dependencies
- 📚 [guide] Replace reorder-python-imports with isort

📚 Replace reorder-python-imports with isort

---

docs/guide.rst

See #1002 and https://github.com/cjolowicz/cookiecutter-hypermodern-python-instance/pull/764

📚 [guide] Document that Typeguard runs on the latest Python only

---

{{cookiecutter.project_name}}/docs/conf.py

Closes #1109.
Fixes the docs' copyright notice by using the author template variable.

Use author template variable in docs' copyright

---

{{cookiecutter.project_name}}/noxfile.py

As of 2.17, [pre-commit prepends a `#!/bin/sh` to its hooks under Windows](https://github.com/pre-commit/pre-commit/pull/2187/files). This breaks `noxfile.py` since `activate_virtualenv_in_precommit_hooks` only matches on `bash` in the first line of the script. I added a `sh` key to `headers` and that seems to have resolved the issue at my end.
https://github.com/pre-commit/pre-commit/issues/2182
https://github.com/pre-commit/pre-commit/pull/2187/commits

Fix Windows support by handling `sh` shebangs from pre-commit

---

{{cookiecutter.project_name}}/README.md

There was an orphaned reference lying around to the cookiecutter project with no associated hyperlink.

Remove unused reference to cookiecutter project

---

docs/conf.py

Badgen frequently returns HTTP 500, failing CI.

📚 [conf] Ignore badgen.net when checking links

---

.github/workflows/constraints.txt
docs/guide.md

* Upgrade Poetry to fix an error because the project uses lock file format version 2.0.
* Remove broken link to `mypy --show-error-codes` from the documentation. The option still exists, but the documentation target is gone, and the behavior is the default with newer versions of mypy.
* Upgrade nox-poetry to fix broken builds due to a change in enum formatting in newer Python versions.

CI: Upgrade Poetry and nox-poetry

---

docs/guide.md
docs/index.md
docs/quickstart.md

Because this does not work on Windows, and Windows users would get a negative user experience when copying and pasting the command from the docs without knowing or thinking of that problem.

Remove the line continuation char in the docs

---

README.md

removed '$' so the command is correct in the convenience of directly copying to CLI
I am aware that the documentation also uses '$' as a marker for "this is a terminal input" and I guess it's by choice. 
The change proposed here in the repository readme is that it's a long phrase with possibilities of typos and should get users running with low friction. One frictionless way is to click the copy button of the code cell and paste in your terminal.

Remove prompt character from README

---

README.md

Replaced the link for dependabot link
fixes: https://github.com/cjolowicz/cookiecutter-hypermodern-python/issues/1186

changed dependabot link
